/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is generated by scripts/generate-components.js
 * Run: node scripts/generate-components.js
 * 
 * To add a new component:
 * 1. Create your component folder: components/YourComponent/
 * 2. Add YourComponent.tsx, example.json, and index.ts
 * 3. Run: node scripts/generate-components.js
 * 4. Done! Component is auto-registered.
 */

// Import all components
import { Button } from './components/Button';
import { Card } from './components/Card';
import { List } from './components/List';
import { Text } from './components/Text';
import { TextInput } from './components/TextInput';

// Import all component examples
import buttonExample from './components/Button/example.json';
import cardExample from './components/Card/example.json';
import listExample from './components/List/example.json';
import textExample from './components/Text/example.json';
import textinputExample from './components/TextInput/example.json';

// Component registry for rendering
export const COMPONENT_REGISTRY = {
  button: Button,
  card: Card,
  list: List,
  text: Text,
  textinput: TextInput,
} as const;

// Example registry for AI prompts
export const EXAMPLE_REGISTRY = {
  button: buttonExample,
  card: cardExample,
  list: listExample,
  text: textExample,
  textinput: textinputExample,
} as const;

// Export individual components
export { Button, Card, List, Text, TextInput };
