/**
 * Component Loader
 * 
 * Loads components from the auto-generated registry.
 * The registry is generated by: node scripts/generate-components.js
 */

import { COMPONENT_REGISTRY, EXAMPLE_REGISTRY } from './components-generated';
import type { ComponentRegistry } from './types';

/**
 * Load all registered components
 */
export function loadComponents(): ComponentRegistry {
  return COMPONENT_REGISTRY as unknown as ComponentRegistry;
}

/**
 * Get component metadata including example
 */
export function getComponentMetadata(componentName: string) {
  return {
    name: componentName,
    example: EXAMPLE_REGISTRY[componentName as keyof typeof EXAMPLE_REGISTRY] || null,
    available: componentName in COMPONENT_REGISTRY,
  };
}

/**
 * Get all available component names
 */
export function getAvailableComponents(): string[] {
  return Object.keys(COMPONENT_REGISTRY);
}

/**
 * Get all component examples for AI prompt generation
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getAllComponentSchemas(): Record<string, any> {
  return EXAMPLE_REGISTRY;
}
